services:

    jt.ads.mailer:
        class: JT\AdsBundle\Mailer\Mailer
        arguments:
            - "@mailer"
            - "@templating"
            - "@=container.has('some_param') ? get('some_param') : 'default_value'"
