<?php

namespace JT\AdsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdsRepository extends EntityRepository
{
	/**
	 * Logic wants newest ads are at the top.
	 */
	public function findAll()
	{
		return $this->findBy(array(), array('createdAt' => 'DESC'));
	}
	
	
	public function findByParameters(array $data, array $sortBy = null){
		
		$query = $this
			->createQueryBuilder('a');
			
		/*
		 * KEYWORDS 
		 */
		if(!empty($data['keywords'])){
			$words = preg_split("#[^a-z]+#", $data['keywords']);
			$imax = sizeof($words);
			for ($i=0 ; $i<$imax ; $i++){
				if (strlen($words[$i]) >= 3)
					$query
						->andWhere('a.title LIKE :word'.$i)
						->setParameter(':word'.$i, '%'.$words[$i].'%');
			}
			
		}
		
		/*
		 * PRICES
		 */
		if(null !== $data['minPrice']){
			$query
				->andWhere('a.price >= :minPrice')
				->setParameter(':minPrice', $data['minPrice']);
		}
		
		if(null !== $data['maxPrice']){
			$query
			->andWhere('a.price <= :maxPrice')
			->setParameter(':maxPrice', $data['maxPrice']);
		}
		
		/*
		 * SORT of entities 
		 */
		switch ($data['sortBy']){
			case 1:
				$query->orderBy('a.price', 'ASC');
				break;
			case 2:
				$query->orderBy('a.price', 'DESC');
				break;
			default:
				$query->orderBy('a.createdAt', 'DESC');
		}
		
		return $query->getQuery()->getResult();
	}
}
