<?php

namespace JT\AdsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends EntityRepository
{
	public function getNotesAverage(\JT\UserBundle\Entity\User $user){
		
		$qb = $this->createQueryBuilder('v');
		$result = $qb
			->select('COUNT(v.note) as nb, SUM(v.note) as total')
			->leftjoin('v.user', 'u')
			->where('u = :user')
				->setParameter('user', $user)
			->getQuery()
			->getResult()
		;
		
		$average = (int)$result[0]['total'] / (int)$result[0]['nb'];
		
		return round($average, 1, PHP_ROUND_HALF_UP);
	}
}
